import { TENURE_CHARGE } from "./tenure-charge.constant";

export const TENURE = [
    { key: 'ASY', inUse: true, isLeasehold: false, charged: TENURE_CHARGE.WEEKLY, label: 'Asylum seeker' },
    { key: 'COM', inUse: true, isLeasehold: false, charged: TENURE_CHARGE.WEEKLY, label: 'Commercial let' },
    { key: 'DEC', inUse: true, isLeasehold: false, charged: TENURE_CHARGE.WEEKLY, label: 'Temp Decant' },
    { key: 'FRE', inUse: true, isLeasehold: true, charged: TENURE_CHARGE.NONE, label: 'Freehold' },
    { key: 'FRS', inUse: true, isLeasehold: true, charged: TENURE_CHARGE.MONTHLY, label: 'Freehold (service charge)' },
    { key: 'HPH', inUse: false, isLeasehold: false, charged: TENURE_CHARGE.NONE, label: 'HPH(SLA)' },
    { key: 'INT', inUse: true, isLeasehold: false, charged: TENURE_CHARGE.WEEKLY, label: 'Introductory' },
    { key: 'LEA', inUse: true, isLeasehold: true, charged: TENURE_CHARGE.MONTHLY, label: 'Leasehold (RTB)' },
    { key: 'LHS', inUse: true, isLeasehold: true, charged: TENURE_CHARGE.MONTHLY, label: 'Leasehold 100% stair' },
    { key: 'LTA', inUse: true, isLeasehold: false, charged: TENURE_CHARGE.WEEKLY, label: 'License temporay account' },
    { key: 'MPA', inUse: true, isLeasehold: false, charged: TENURE_CHARGE.WEEKLY, label: 'Mesne profit account' },
    { key: 'NON', inUse: true, isLeasehold: false, charged: TENURE_CHARGE.WEEKLY, label: 'Non-secure' },
    { key: 'PVG', inUse: true, isLeasehold: false, charged: TENURE_CHARGE.WEEKLY, label: 'Private garage' },
    { key: 'RSL', inUse: false, isLeasehold: false, charged: TENURE_CHARGE.NONE, label: 'Landlord' },
    // used for advertising non-LBH property
    { key: 'RTM', inUse: true, isLeasehold: true, charged: TENURE_CHARGE.MONTHLY, label: 'Rent to mortgage' },
    { key: 'SEC', inUse: true, isLeasehold: false, charged: TENURE_CHARGE.WEEKLY, label: 'Secure' },
    { key: 'SHO', inUse: true, isLeasehold: true, charged: TENURE_CHARGE.MONTHLY, label: 'Shared ownership' },
    { key: 'SLL', inUse: true, isLeasehold: false, charged: TENURE_CHARGE.WEEKLY, label: 'Short life lease' },
    { key: 'SPS', inUse: true, isLeasehold: true, charged: TENURE_CHARGE.MONTHLY, label: 'Private sale leasehold' },
    { key: 'SPT', inUse: false, isLeasehold: false, charged: TENURE_CHARGE.NONE, label: 'Sheltered accommodation' },
    { key: 'SSE', inUse: true, isLeasehold: true, charged: TENURE_CHARGE.MONTHLY, label: 'Share equity' },
    { key: 'TAF', inUse: true, isLeasehold: false, charged: TENURE_CHARGE.NONE, label: 'Tenants association flat' },
    { key: 'TBB', inUse: true, isLeasehold: false, charged: TENURE_CHARGE.WEEKLY, label: 'Temporary B&B' },
    { key: 'TGA', inUse: true, isLeasehold: false, charged: TENURE_CHARGE.WEEKLY, label: 'Tenant garage' },
    { key: 'THL', inUse: true, isLeasehold: false, charged: TENURE_CHARGE.WEEKLY, label: 'Temporary hostel lease' },
    { key: 'THO', inUse: true, isLeasehold: false, charged: TENURE_CHARGE.WEEKLY, label: 'Temporary hostel' },
    { key: 'TLA', inUse: true, isLeasehold: false, charged: TENURE_CHARGE.WEEKLY, label: 'Temporary annex' },
    { key: 'TPL', inUse: true, isLeasehold: false, charged: TENURE_CHARGE.WEEKLY, label: 'Temporary private let' },
    { key: 'TRA', inUse: true, isLeasehold: false, charged: TENURE_CHARGE.WEEKLY, label: 'Temporary Traveller' },
    { key: null, inUse: true, isLeasehold: false, charged: TENURE_CHARGE.WEEKLY, label: 'Temp Traveller' },
];
