export const TENURE_CHARGE = {
    WEEKLY: 'week',
    MONTHLY: 'month',
    NONE: 'none'
};

export const TENURE = [
    { key: 'ASY', charged: TENURE_CHARGE.WEEKLY, label: 'Asylum seeker' },
    { key: 'COM', charged: TENURE_CHARGE.WEEKLY, label: 'Commercial let' },
    { key: 'DEC', charged: TENURE_CHARGE.WEEKLY, label: 'Temp Decant' },
    { key: 'FRE', charged: TENURE_CHARGE.NONE, label: 'Freehold' },
    { key: 'FRS', charged: TENURE_CHARGE.MONTHLY, label: 'Freehold (service charge)' },
    { key: 'HPH', charged: TENURE_CHARGE.NONE, label: 'HPH(SLA)' },
    { key: 'INT', charged: TENURE_CHARGE.WEEKLY, label: 'Introductory' },
    { key: 'LEA', charged: TENURE_CHARGE.MONTHLY, label: 'Leasehold (RTB)' },
    { key: 'LHS', charged: TENURE_CHARGE.MONTHLY, label: 'Leasehold 100% stair' },
    { key: 'LTA', charged: TENURE_CHARGE.WEEKLY, label: 'License temporay account' },
    { key: 'MPA', charged: TENURE_CHARGE.WEEKLY, label: 'Mesne profit account' },
    { key: 'NON', charged: TENURE_CHARGE.WEEKLY, label: 'Non-secure' },
    { key: 'PVG', charged: TENURE_CHARGE.WEEKLY, label: 'Private garage' },
    { key: 'RSL', charged: TENURE_CHARGE.NONE, label: 'Landlord' },
    { key: 'RTM', charged: TENURE_CHARGE.MONTHLY, label: 'Rent to mortgage' },
    { key: 'SEC', charged: TENURE_CHARGE.WEEKLY, label: 'Secure' },
    { key: 'SHO', charged: TENURE_CHARGE.MONTHLY, label: 'Shared ownership' },
    { key: 'SLL', charged: TENURE_CHARGE.WEEKLY, label: 'Short life lease' },
    { key: 'SPS', charged: TENURE_CHARGE.MONTHLY, label: 'Private sale leasehold' },
    { key: 'SPT', charged: TENURE_CHARGE.NONE, label: 'Sheltered accommodation' },
    { key: 'SSE', charged: TENURE_CHARGE.MONTHLY, label: 'Share equity' },
    { key: 'TAF', charged: TENURE_CHARGE.NONE, label: 'Tenants association flat' },
    { key: 'TBB', charged: TENURE_CHARGE.WEEKLY, label: 'Temporary B&B' },
    { key: 'TGA', charged: TENURE_CHARGE.WEEKLY, label: 'Tenant garage' },
    { key: 'THL', charged: TENURE_CHARGE.WEEKLY, label: 'Temporary hostel lease' },
    { key: 'THO', charged: TENURE_CHARGE.WEEKLY, label: 'Temporary hostel' },
    { key: 'TLA', charged: TENURE_CHARGE.WEEKLY, label: 'Temporary annex' },
    { key: 'TPL', charged: TENURE_CHARGE.WEEKLY, label: 'Temporary private let' },
    { key: 'TRA', charged: TENURE_CHARGE.WEEKLY, label: 'Temporary Traveller' },
    { key: null, charged: TENURE_CHARGE.WEEKLY, label: 'Temp Traveller' },
];
