export const PAGES = {
    PREVIOUS_CALLS: { route: 'home', label: 'My home' },
    LOG_CALL: { route: 'log-call', label: 'Start new call' },
    IDENTIFY: { route: 'identify', label: 'Identify caller' },
    IDENTIFY_ADDRESSES: { route: 'addresses', label: 'Caller Identification' },
    IDENTIFY_TENANTS: { route: 'tenants', label: 'Caller Identification' },
    ADDITIONAL_REASON: { route: 'log-additional', label: 'Add another call reason' },
    VIEW_NOTES: { route: 'view-notes', label: 'See caller notes' },
    COMMS: { route: 'comms', label: 'Send emails, texts, and letters' },
    RENT: { route: 'rent', label: 'Rent' },
    RENT_SUMMARY: { route: 'summary', label: 'Statement' },
    RENT_TRANSACTIONS: { route: 'transactions', label: 'Transaction History' },
    RENT_PAYMENT: { route: 'make', label: 'Pay Rent' },
    RENT_COMMS: { route: 'comms', label: 'Communications' },
    RENT_STATEMENT: { route: 'statement', label: 'Statement Preview' },
    REQUEST_CALLBACK: { route: 'callback', label: 'Request a callback' },
    EDIT_CONTACT_DETAILS: { route: 'contact-details', label: 'Edit Contact Details' },
    AUTHENTICATION: { route: 'auth', label: '' },
    TRANSACTION: { route: 'transaction', label: '' },
    TRANSACTION_SUCCESS: { route: 'success', label: 'Successful Transaction' },
    TRANSACTION_FAILED: { route: 'failed', label: 'Failed Transaction' },
    TRANSACTION_ERROR: { route: 'error', label: 'Problem Making Payment' },
    TRY_AGAIN: { route: 'try-again', label: 'Access Error' },
    PLAYGROUND: { route: 'playground', label: 'Playground' },
};
