export const TENURE = [
    { key: 'ASY', label: 'Asylum seeker' },
    { key: 'COM', label: 'Commercial let' },
    { key: 'DEC', label: 'Temp Decant' },
    { key: 'DEC', label: 'Temporay decant' },
    { key: 'FRE', label: 'Freehold' },
    { key: 'FRS', label: 'Freehold (service charge)' },
    { key: 'HPH', label: 'HPH(SLA)' },
    { key: 'INT', label: 'Introductory' },
    { key: 'LEA', label: 'Leasehold (RTB)' },
    { key: 'LHS', label: 'Leasehold 100% stair' },
    { key: 'LTA', label: 'License temporay account' },
    { key: 'MPA', label: 'Mesne profit account' },
    { key: 'NON', label: 'Non-secure' },
    { key: 'PVG', label: 'Private garage' },
    { key: 'RSL', label: 'Landlord' },
    { key: 'RTM', label: 'Rent to mortgage' },
    { key: 'SEC', label: 'Secure' },
    { key: 'SHO', label: 'Shared ownership' },
    { key: 'SLL', label: 'Short life lease' },
    { key: 'SPS', label: 'Private sale leasehold' },
    { key: 'SPT', label: 'Sheltered accommodation' },
    { key: 'SSE', label: 'Share equity' },
    { key: 'TAF', label: 'Tenants association flat' },
    { key: 'TBB', label: 'Temporary B&B' },
    { key: 'TGA', label: 'Tenant garage' },
    { key: 'THL', label: 'Temporary hostel lease' },
    { key: 'THO', label: 'Temporary hostel' },
    { key: 'TLA', label: 'Temporary annex' },
    { key: 'TPL', label: 'Temporary private let' },
    { key: 'TRA', label: 'Temporary Traveller' },
    { key: null, label: 'Temp Traveller' },
];
